### ISSUE TITLE
Disable the report button fully in both the pause and player menu

### ISSUE THREAD

**Issue by CutieAshlynn** [Doclic/NoEncryption#107]
### Is there an existing enhancement issue for this?

- [X] I have searched the existing enhancement issues and have not found a duplicate relating to my request.

### Purpose of New Feature

Since the chat signing is fully disabled i think that adding this could help a lot so people wont report other users even if the chat signing is no longer enabled and i also think this feature could help a lot incase somehow even tho the chat signing is disabled a user gets reported then gets banned by mojang.

### Behavior of New Feature

This new feature would help people not report chat messages to mojang even though the chat signing is disabled this would solve the problem of people trying to mass report users for something random and it would work by disabling the chat report button fully in the pause menu and the player menu.

### Would this new feature interfere with any existing functionalities of NoEncryption?

- [x] I do not believe this feature would affect NoEncryption's existing functions.

### Anything else?

I dont know if this feature is added fully because when i went to play my server with the plugin the chat signing was disabled and both chat report buttons were fully working.

**Comment by doclic** [comment]
Unfortunately, it is not possible for server-side plugins such as NoEncryption to do this
The button is added by the game client and only client-side mods such as NoChatReports can disable it
