### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by ClayCoffee** [Doclic/NoEncryption#109]
### Is there an existing enhancement issue for this?

- [X] I have searched the existing enhancement issues and have not found a duplicate relating to my request.

### Purpose of New Feature

1.20 support

### Behavior of New Feature

can work on Minecraft 1.20

### Would this new feature interfere with any existing functionalities of NoEncryption?

- [X] I do not believe this feature would affect NoEncryption's existing functions.

**Comment by whytf** [comment]
Bump

**Comment by doclic** [comment]
It's done, creating a GitHub release in a few minutes

**Comment by ClayCoffee** [comment]
it has been 6 hours, no new release @Doclic

**Comment by doclic** [comment]
> it has been 6 hours, no new release @Doclic

yeah the github workflows are not working for whatever reason
there's a build in the discord if you want one now

**Comment by whytf** [comment]
Well the github action failed

**Comment by whytf** [comment]
> > it has been 6 hours, no new release @Doclic
> 
> yeah the github workflows are not working for whatever reason there's a build in the discord if you want one now

Well the github workflow failed @Doclic
