### ISSUE TITLE
Kicked for Internal Excecption

### ISSUE THREAD

**Issue by mega12345mega** [Doclic/NoEncryption#11]
When sending a message in chat, all players are kicked for:
`Internal Exception: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.d()'`

This may be directly related to [Issue #10](https://github.com/Doclic/NoEncryption/issues/10), as I'm running Spigot 1.19.1.
However, the fact that I'm getting a `java.lang.NoSuchMethodError` as opposed to a `java.lang.NoClassDefFoundError` makes it possible the issue is instead caused by the mappings getting updated for 1.19.1, as this is using NMS.

After a brief look through the source code, I think the error is coming from [CompatiblePacketListener_v1_19_R1.java#L20](https://github.com/Doclic/NoEncryption/blob/d70c51cacd155e2742aa6e506ffbf9d6403ee0c6/src/main/java/me/doclic/noencryption/compatibility/v1_19_R1/CompatiblePacketListener_v1_19_R1.java#L20)

There are no errors in the console :/

**Comment by V1nc3ntWasTaken** [comment]
Already patched with addition of 1.19.1 support (#20)

Will be available in release 3.0
