### ISSUE TITLE
When I type anything in chat, I get kicked

### ISSUE THREAD

**Issue by SpiritOTHawk** [Doclic/NoEncryption#16]
When I type anything in chat, I get kicked for:

Internal Exception: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.d()'

Server version: 1.19.2
Tested client versions: 1.19.2, 1.19.1

I'm using paper

**Comment by V1nc3ntWasTaken** [comment]
Hi, currently, 1.19.1 and 1.19.2 is not released yet. Although, you can check in the PR section (pull requests) for a 1.19.1 and 1.19.2 version from my fork. (**Not trying to self promote, just offering a temporary solution until this repository is updated to the latest version. If the owner of this plugin has any conflicts with this, please feel free to delete these messages**)

**Comment by V1nc3ntWasTaken** [comment]
Already patched with addition of 1.19.1 support (#20), and 1.19.2 support (#22)

Will be available in release 3.0
