### ISSUE TITLE
Kick everyone on server with /annouce command.

### ISSUE THREAD

**Issue by Ativ3k** [Doclic/NoEncryption#17]
When i use /annouce command everyone in server gets kicked.

Console log:
  [Sat 18:01:01 INFO  Server/PlayerConnection] Ativ3k issued server command: /announce s
  [Sat 18:01:01 INFO ] s
  [Sat 18:01:01 INFO  Server/PlayerConnection] Ativ3k lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
  
Is it possible that the plugin collides with another plugin? After unload/disable this plugin annouce command works correctly.

**Comment by V1nc3ntWasTaken** [comment]
What NoEncryption version are you using??

**Comment by Ativ3k** [comment]
NoEncryption-v3.1--1.19.2_only
My issue was here: #4 
i update to NoEncryption-v4.0--1.19.2_only and now works
thanks
