### ISSUE TITLE
EssentialsX Blacklist

### ISSUE THREAD

**Issue by V1nc3ntWasTaken** [Doclic/NoEncryption#24]
Plugin blacklisted internally in Essentials plugin

[EssentialsX/Essentials #5036](https://github.com/EssentialsX/Essentials/pull/5036)

**Comment by AffectedArc07** [comment]
I should point out the plugin isnt "blacklisted" per say. It will still load just fine, just throw up a warning on startup about it being there because it uses reflection and isnt modular between versions.

Plugin will still function with Essentialls installed

**Comment by Doclic** [comment]
ViaVersion does this aswell
```java
list.add(new UnsupportedPlugin.Builder().name("software to mess with message signing").reason(UnsupportedPlugin.Reason.SECURE_CHAT_BYPASS)
                .addPlugin("NoEncryption").addPlugin("NoReport")
                .addPlugin("NoChatReports").addPlugin("NoChatReport").build());```
