### ISSUE TITLE
[Suggestion] Add config for not converting to system messages

### ISSUE THREAD

**Issue by Reimnop** [Doclic/NoEncryption#27]
Because I'd like to use chatheads client-side, but this mod strips all player data from the message, presumably to avoid the ugly red strip and exclamation mark. However there are mods that disable those so it'd be nice for such an option to exist for people who want it.

**Comment by V1nc3ntWasTaken** [comment]
Hi, I was wondering if you had links to any of these mods so I can test it on my end of things. Thanks!

**Comment by Reimnop** [comment]
Sure

[Chat Heads](https://www.curseforge.com/minecraft/mc-mods/chat-heads)

[Gatekeep (chat indicator remover)](https://modrinth.com/mod/gatekeep)

**Comment by V1nc3ntWasTaken** [comment]
### So, from my testing...

## [Chat Heads](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
Chat Heads works perfectly fine for me with NoEncryption installed. Note, this is a fresh install of [Chat Heads 0.7.1 for Forge 1.19.1+](https://www.curseforge.com/minecraft/mc-mods/chat-heads/files/3923445)
![image](https://user-images.githubusercontent.com/79623093/191592697-cbed3f6d-0299-4a85-8868-004d7b30a89f.png "2 way message with NoEncryption 3.0 with Chat Heads working")

Without Chat Heads mod
![image](https://user-images.githubusercontent.com/79623093/191593848-4ebef563-baf0-4d8f-bb5c-5f5411b2a9a3.png "2 way message with NoEncryption 3.0 with Chat Heads disabled")

With Chat Heads and without NoEncryption
![image](https://user-images.githubusercontent.com/79623093/191596505-e1aab5d4-8f45-4621-bd74-aaa899656195.png "2 way message with NoEncryption 3.0 disabled and Chat Heads enabled")


## [Gatekeeper](https://modrinth.com/mod/gatekeep)
Gatekeeper works perfectly fine for me with NoEncryption installed. Note, this is a fresh install of [Gatekeeper 1.1.1 for Fabric 1.19.1-1.19.2](https://github.com/thirdsanctuary/gatekeep/releases/tag/1.1.1)
![image](https://user-images.githubusercontent.com/79623093/191595294-3cf8c996-e2d3-4e45-aca7-4c20f04dcd53.png "2 way message with NoEncryption 3.0 with Gatekeeper working")

Without Gatekeeper mod
![image](https://user-images.githubusercontent.com/79623093/191595442-fe89935f-3b24-4c64-9d95-e0c2318ede4e.png "2 way message with NoEncryption 3.0 with Gatekeeper disabled")

With Gatekeeper and without NoEncryption
![image](https://user-images.githubusercontent.com/79623093/191595733-19f500c2-81d4-4b85-a960-cd38c9b47006.png "2 way message with NoEncryption 3.0 disabled and Gatekeeper enabled")

## Files
Files I tested with are attached below, and their VirusTotal + Checksums linked below.

<br>

### [gatekeeper-1.1.1.jar.zip](https://github.com/Doclic/NoEncryption/files/9619934/gatekeep-1.1.1.jar.zip)
[VirusTotal Report](https://www.virustotal.com/gui/file/bd8a2f2133cb8faf3efc8aba992a3858af24faf3f0ba54b71784175e5daa3ef4/detection)
MD5: **c0a9324afed58e3b6a2aab5b4e7a4298**
SHA-1 :**231de43ca96aa0a664255d259c4884208eb2b5b3**
SHA-256: **bd8a2f2133cb8faf3efc8aba992a3858af24faf3f0ba54b71784175e5daa3ef4**

<br>

### [chat_heads-0.7.1-forge-1.19.1.jar.zip](https://github.com/Doclic/NoEncryption/files/9619927/chat_heads-0.7.1-forge-1.19.1.jar.zip)
[VirusTotal](https://www.virustotal.com/gui/file/1f1b8274dbe09512ff53d90d6d5677035aefb410c58b24e0aee3bdf3f5efe32e/detection)
MD5: 3f2ca90d6e2d34c7e233d4cc28d1832c
SHA-1: be82e993ab293e67b12428cc87a9e91f45a7c3a6
SHA-256: 1f1b8274dbe09512ff53d90d6d5677035aefb410c58b24e0aee3bdf3f5efe32e

**Comment by Reimnop** [comment]
Have you tested chat heads with special formatting? Maybe even nicknames? It tends to struggle with that.
