### ISSUE TITLE
Use Reflection so Plugin won't break with every new update

### ISSUE THREAD

**Issue by TheJeterLP** [Doclic/NoEncryption#31]
Currently you have to change your Compatibility class with every new version and basically copy the whole plugin with every new Minecraft version. This shouldnt be done since the Plugin will break with every MC update. Use Reflection instead to get the classes that you need dynamically.

**Comment by V1nc3ntWasTaken** [comment]
This is something that I plan on doing in the near future, I am just working on getting a little more comfortable with learning and using reflection.

**Comment by kralverde** [comment]
Does reflection in mc use the spigot translated names or the original obfuscated names?

**Comment by V1nc3ntWasTaken** [comment]
Currently the plugin uses remapped, spigot-translated names as maven dependencies to handle and re-form packets, that then get transformed back to minecraft obfuscated mappings once the project is built and compiled.

**Comment by Doclic** [comment]
This will be included in 5.0, see #41
