### ISSUE TITLE
1.19.3 Update

### ISSUE THREAD

**Issue by itinstructor** [Doclic/NoEncryption#34]
This plugin seems to be broken with 1.19.3. It doesn't load.

**Comment by V1nc3ntWasTaken** [comment]
Yeah, I gotta write some new stuff for it. Minecraft rewrote some of the chat stuff as well as added chat deleting. Needs a little bit of work done

**Comment by mekb-turtle** [comment]
they added chat deleting? how does that work? does it work for system messages too?

**Comment by Impactic48** [comment]
Any update on this?

**Comment by V1nc3ntWasTaken** [comment]
Closed with release [4.0](https://github.com/Doclic/NoEncryption/releases/tag/4.0-real)
