### ISSUE TITLE
1.19.3 Update

### ISSUE THREAD

**Issue by Vertical149** [Doclic/NoEncryption#35]
It's not working for 1.19.3. Can I know when will the update come so it works for 1.19.3??

**Comment by Noobymen** [comment]
dont know why it's not been updated already 1.19.3 was released already more then one month ago
is there anywhere that i can maybe donated to maybe help with making the process faster
because this plugin is very much needed in my server it helps greatly happy that you made it in the first place

**Comment by Z1xus** [comment]
maybe it's not the same but you should check out [FreedoomChat plugin](https://github.com/e-im/FreedomChat)

**Comment by czhangdev** [comment]
Duplication of #34
> Yeah, I gotta write some new stuff for it. Minecraft rewrote some of the chat stuff as well as added chat deleting. Needs a little bit of work done

**Comment by V1nc3ntWasTaken** [comment]
Closed with release [4.0](https://github.com/Doclic/NoEncryption/releases/tag/4.0-real)
