### ISSUE TITLE
Velocity kicking players for not having a signed message

### ISSUE THREAD

**Issue by Impactic48** [Doclic/NoEncryption#36]
Sometimes when a player talks in chat they will get kicked with the error message listed in the logs below. 

Version: Purpur 1.19.2
Video: https://youtu.be/zLOxXsJ2Y8I
Log file: https://mclo.gs/J9ZT0Ye

**Comment by V1nc3ntWasTaken** [comment]
I will do some further research to see if this is an avoidable problem for Velocity.

**Comment by V1nc3ntWasTaken** [comment]
If possible, can you please describe a way to recreate this, and send me info such as plugin version, server version, velocity version, server type, etc.

**Comment by Impactic48** [comment]
> If possible, can you please describe a way to recreate this, and send me info such as plugin version, server version, velocity version, server type, etc.

Server Version: Purpur 1.19.2
Velocity Version:  3.20-SNAPSHOT

Plugins on proxy and backend: LiteBans (LiteBans is causing this issue)
Plugins on backend: NoEncryption 1.19.2

How to recreate: 
1. Mute player
2. Get player to send a message in chat
3. It should kick player with the message shown

**Comment by V1nc3ntWasTaken** [comment]
So, upon further testing, I have tried this with LiteBans tied over a database on a proxy running [Velocity Build 229](https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/229/downloads/velocity-3.2.0-SNAPSHOT-229.jar) and on a server running [Purpur Build 1858 for 1.19.2](https://api.purpurmc.org/v2/purpur/1.19.2/1858/download) and it looks like that this is a LiteBans problem. 

The console message `A plugin tried to cancel a signed chat message`... and player disconnect message `A proxy plugin caused an illegal protocol state.`... kinda debunk this issue in a way, saying that a proxy plugin is the issue. On the server console side of things, I am only provided with `V1nc3ntWasTaken lost connection: Disconnected` which indicates that a disconnect status was sent to the server, and not a `Lost Connection` status. I tested this with and without [NoEncryption v4.1 for 1.19.2](https://github.com/Doclic/NoEncryption/releases/tag/4.1) on the backend.

I went ahead and made an issue on the LiteBans GitLab which can be found [here](https://gitlab.com/ruany/LiteBans/-/issues/497).

**Comment by V1nc3ntWasTaken** [comment]
So it looks like the issue created on the LiteBans GitLab was closed, but provided a possible solution to your problem.

`Installing LiteBans under the backend servers - if you still need LiteBans on the proxy instance, you can disable mutes in the configuration to have mutes enforced by the backend instances instead of Velocity.`
