### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by Gyztor** [Doclic/NoEncryption#6]
From what i have heard the banning will also be able to be done on servers that are older but use something like viaversion/viabackwards and other similar things and this mod isn't install-able on 1.18.2 allowing people to report people on your server still if they use a later version. would it be possible to add some backwards compatibility. like 1.18.2, 1.17.1 and 1.16.5 (and maybe more in the future if needed/wanted) this would protect servers that also use viaversion/viabackwards too. Maybe making something that works on bungee and waterfall would also work? for multi versions (at least as a temporary thing) as it would strip the encryption at bungee level rather than just spigot/paper level.

**Comment by Doclic** [comment]
Pre-1.19 clients won't send chat signatures, so those won't be able to be reported
1.19 clients will send their signatures but it's likely (I didn't check) that ViaVersion won't send the signatures back, as this seems unnecessary; so if you're using ViaVersion, I don't think your players would get banned.

I'll try to check if ViaVersion does send signatures later, and if it does, I'll remove those too.

**Comment by Gyztor** [comment]
alright, sounds good. I have checked at least in their update logs to see if they added anything of the sort and they don't seem to have, but i still do have one concern. 1.19 bungeecord/waterfall and their respective forks. they still do in fact take signatures (at least from what i have seen and it doesn't matter if the backend server is 1.19 or not) and so will this plugin be eventually made to also work on the 1.19 bungeecord/waterfall? Or is this not planned for the time being?

**Comment by NotAHolyPerson** [comment]
Probably will be done in 2.1.
Unsure if Doclic confirms it, but I think so.

**Comment by Doclic** [comment]
I've never worked with Bungeecord before, but I'll try

**Comment by Creeperz653** [comment]
Add support to velocity first because it is recommended by paper

**Comment by V1nc3ntWasTaken** [comment]
The original question has been answered. In terms of the comment from @Creeperz653, I have created a new issue addressing Velocity and BungeeCord support. See #42
