### ISSUE TITLE
Player gets kicked when using /msg

### ISSUE THREAD

**Issue by Wolfcoool** [Doclic/NoEncryption#7]
Plugin version: NoEncryption-v1.1--1.19_only
Minecraft version: 1.19
Paper version: git-Paper-39
Plugin list: ConsoleSpamFix, CoreProtect, DiscordSRV, InventoryRollbackPlus, LuckPerms, NoEncryption, SuicideKill, TAB, TCPShield.

Player kick message : Internal Exception: java.lang.IllegalAccessException: Can not set final net.minecraft.util.MinecraftEncryption$b field net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.f to null value

Also I was just messaging myself (/msg wolfcoool test) but it works without the plugin so that shouldn't be the issue. 

Edit: Also, using EssentialsX's /msg seems to work  for anyone else who also is having this error.

**Comment by jacobvd0** [comment]
Did you download the plugin from spigot? If so, download it from github (https://github.com/Doclic/NoEncryption/releases/tag/1.1) as I don't believe the developer has updated it on Spigot yet.

**Comment by Doclic** [comment]
No, the issue is that it wasn't fixed properly. I _hopefully_ actually fixed it this time.
