### ISSUE TITLE
[Suggestion] Implement a visible signature-strip marker

### ISSUE THREAD

**Issue by tabernacle8** [Doclic/NoEncryption#8]
### **Is your feature request related to a problem? Please describe:** 

It's always hard to identify whether a signature-stripping plugin is working correctly or not without any quick and easy way to tell. 
This can lead to decreased trust in a plugin and many people cannot read or have the time to audit source code on their own.

### **Describe the solution you'd like. A clear and concise description of what you want to happen.**

Perhaps some sort of indicator in chat, _toggleable in a config_, can be made to either add a prefix to signature-stripped messages or change the sender's name's color. Something, probably, nonintrusive yet visible.

### **Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.**

Alternative solutions might include the following:

1. Sending a message that the plugin is working to admins on login
2.  Kicking incompatible players

### **Additional context. Add any other context or screenshots about the feature request here.**

A possible preview of what this could look like in production has been attached below:
![image](https://user-images.githubusercontent.com/19417482/179123096-68dc0511-cc84-41bd-a046-0d5f23336b35.png)

**Comment by Mitsu13Ion** [comment]
just to say I agree with him

**Comment by Doclic** [comment]
imo, this doesn't really fix this problem, as you could just say that the plugin always adds the checkmark, because well it does
i'm working on making every message a system message, so players won't even be able to select the messages for reporting, so i think that will be enough of a proof

**Comment by tabernacle8** [comment]
> imo, this doesn't really fix this problem, as you could just say that the plugin always adds the checkmark, because well it does i'm working on making every message a system message, so players won't even be able to select the messages for reporting, so i think that will be enough of a proof

I agree, this is a much better solution than that originally proposed one. If you could implement that it would definitely fix the original issue. Once that feature gets implemented you should close this issue.

**Comment by Doclic** [comment]
I need to wait for 1.19.1 to release, as the code that I want to use is only available in this version.
