### ISSUE TITLE
Missing signature kick

### ISSUE THREAD

**Issue by kalleswe** [Doclic/NoEncryption#81]
### Are you using the latest version of NoEncryption?

- [X] I am using the latest version of NoEncryption compatible with my server version.

### Is there an existing issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### NoEncryption Version

5.0

### Minecraft Version

1.19.3

### Server Type/Build

Paper latest 1.19.3

### Reproducible Test

Type in chat a few times and get kicked just as it did when chat signature failed. But this time instead it says: "Missing signature" instead, which is kinda expected if you remove the signature from the plugin.

I'm sure this is nothing that you can fix, but reporting it as an issue anyway just to let you know that MS probably made your plugin obsolete.

**Comment by NyaomiDEV** [comment]
Did you set `enforce-secure-profile=false` in your `server.properties`?

**Comment by V1nc3ntWasTaken** [comment]
I just tried that myself with the same results as posted above

**Comment by kiwisap** [comment]
I have the same issue. Could this be related to bungeecord or a fork of bungeecord?
