### ISSUE TITLE
Plugin Doesn't Work, use HighpurityFork

### ISSUE THREAD

**Issue by Highpurity** [Doclic/NoEncryption#9]
I made a much better fork over on my github page and it is significantly better with better optimization, better packet handling, better author name, and more. Please don't hurt me, for legal reasons that was a joke.

**Comment by Doclic** [comment]
true true

**Comment by Highpurity** [comment]
UwU notice me

**Comment by Doclic** [comment]
no

**Comment by Highpurity** [comment]
How was your day

**Comment by Doclic** [comment]
idk
